import React from 'react';
import { AlertCircle, ShieldCheck, HeartPulse } from 'lucide-react';

export default function FooterDisclaimer() {
  return (
    <footer className="w-full mt-16 pb-12 pt-8 border-t border-slate-800/80 text-left">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        
        {/* Clinical Disclaimer Callout */}
        <div className="p-4 sm:p-5 rounded-2xl bg-amber-500/5 border border-amber-500/20 flex items-start gap-3.5 text-xs text-amber-300/90 leading-relaxed">
          <AlertCircle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
          <div>
            <span className="font-bold text-amber-300 uppercase tracking-wide block mb-0.5">
              Medical & Clinical Research Disclaimer
            </span>
            This application is an AI-based screening and educational decision-support tool and is not a replacement for professional clinical ophthalmology diagnosis. Results generated by the MobileNetV2 architecture and Grad-CAM explainability module should always be reviewed by a certified healthcare professional.
          </div>
        </div>

        {/* Footer Bottom Bar */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-cyan-400" />
            <span className="font-semibold text-slate-400">OcuSense Screening Platform</span>
            <span>•</span>
            <span>Final-Year BTech ML Healthcare Architecture</span>
          </div>

          <div className="flex items-center gap-4 font-mono text-[11px]">
            <span>FastAPI Backend</span>
            <span> PyTorch Core</span>
            <span> MobileNetV2</span>
            <span> Grad-CAM</span>
          </div>
        </div>

      </div>
    </footer>
  );
}
